version: "3"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: "npm start"
    links:
      - db
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: focus
    volumes:
      - database_volume:/var/lib/postgresql/data
volumes:
  database_volume: